In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
data=pd.read_csv('ENB2012_Data.csv')
data.dropna(how='all') #remove NaN values from the data set
datanew= data.dropna(axis=1, how='all') #first deletes all the non useful columns from the dataset
data_processed=datanew.dropna(how='all') #then deletes all the unuseful rows from the data set
print(data_processed)
#lets try re-naming all the headers columns
data_finalized=data_processed.rename(columns={"X1": "Relative Compactness", "X2": "Surface Area","X3": "Wall Area","X4": "Roof Area","X5": "Overall Height","X6": "Orientation","X7": "Glazing Area","X8": "Glazing Area Distribution","Y1": "Heating Load","Y2":"Cooling Load"})
data_finalized.head(10) #lets me look at random samples within the dataset


       X1     X2     X3      X4   X5   X6   X7   X8     Y1     Y2
0    0.98  514.5  294.0  110.25  7.0  2.0  0.0  0.0  15.55  21.33
1    0.98  514.5  294.0  110.25  7.0  3.0  0.0  0.0  15.55  21.33
2    0.98  514.5  294.0  110.25  7.0  4.0  0.0  0.0  15.55  21.33
3    0.98  514.5  294.0  110.25  7.0  5.0  0.0  0.0  15.55  21.33
4    0.90  563.5  318.5  122.50  7.0  2.0  0.0  0.0  20.84  28.28
..    ...    ...    ...     ...  ...  ...  ...  ...    ...    ...
763  0.64  784.0  343.0  220.50  3.5  5.0  0.4  5.0  17.88  21.40
764  0.62  808.5  367.5  220.50  3.5  2.0  0.4  5.0  16.54  16.88
765  0.62  808.5  367.5  220.50  3.5  3.0  0.4  5.0  16.44  17.11
766  0.62  808.5  367.5  220.50  3.5  4.0  0.4  5.0  16.48  16.61
767  0.62  808.5  367.5  220.50  3.5  5.0  0.4  5.0  16.64  16.03

[768 rows x 10 columns]


Relative Compactness  Surface Area  Wall Area  Roof Area  Overall Height  \
0                  0.98         514.5      294.0     110.25             7.0   
1                  0.98         514.5      294.0     110.25             7.0   
2                  0.98         514.5      294.0     110.25             7.0   
3                  0.98         514.5      294.0     110.25             7.0   
4                  0.90         563.5      318.5     122.50             7.0   
5                  0.90         563.5      318.5     122.50             7.0   
6                  0.90         563.5      318.5     122.50             7.0   
7                  0.90         563.5      318.5     122.50             7.0   
8                  0.86         588.0      294.0     147.00             7.0   
9                  0.86         588.0      294.0     147.00             7.0   

   Orientation  Glazing Area  Glazing Area Distribution  Heating Load  \
0          2.0           0.0                        0.0         15.55   
1          3.0           0.0                        0.0         15.55   
2          4.0           0.0                        0.0         15.55   
3          5.0           0.0                        0.0         15.55   
4          2.0           0.0                        0.0         20.84   
5          3.0           0.0                        0.0         21.46   
6          4.0           0.0                        0.0         20.71   
7          5.0           0.0                        0.0         19.68   
8          2.0           0.0                        0.0         19.50   
9          3.0           0.0                        0.0         19.95   

   Cooling Load  
0         21.33  
1         21.33  
2         21.33  
3         21.33  
4         28.28  
5         25.38  
6         25.16  
7         29.60  
8         27.30  
9         21.97

In [22]:
x=data_finalized.iloc[:,:-2].values
y=heating_load_y=data_finalized.iloc[:,8:9].values
print(y)


[[15.55]
 [15.55]
 [15.55]
 [15.55]
 [20.84]
 [21.46]
 [20.71]
 [19.68]
 [19.5 ]
 [19.95]
 [19.34]
 [18.31]
 [17.05]
 [17.41]
 [16.95]
 [15.98]
 [28.52]
 [29.9 ]
 [29.63]
 [28.75]
 [24.77]
 [23.93]
 [24.77]
 [23.93]
 [ 6.07]
 [ 6.05]
 [ 6.01]
 [ 6.04]
 [ 6.37]
 [ 6.4 ]
 [ 6.37]
 [ 6.4 ]
 [ 6.85]
 [ 6.79]
 [ 6.77]
 [ 6.81]
 [ 7.18]
 [ 7.1 ]
 [ 7.1 ]
 [ 7.1 ]
 [10.85]
 [10.54]
 [10.77]
 [10.56]
 [ 8.6 ]
 [ 8.49]
 [ 8.45]
 [ 8.5 ]
 [24.58]
 [24.63]
 [24.63]
 [24.59]
 [29.03]
 [29.87]
 [29.14]
 [28.09]
 [26.28]
 [26.91]
 [26.37]
 [25.27]
 [23.53]
 [24.03]
 [23.54]
 [22.58]
 [35.56]
 [37.12]
 [36.9 ]
 [35.94]
 [32.96]
 [32.12]
 [32.94]
 [32.21]
 [10.36]
 [10.43]
 [10.36]
 [10.39]
 [10.71]
 [10.8 ]
 [10.7 ]
 [10.75]
 [11.11]
 [11.13]
 [11.09]
 [11.16]
 [11.68]
 [11.69]
 [11.7 ]
 [11.69]
 [15.41]
 [15.2 ]
 [15.42]
 [15.21]
 [12.96]
 [12.97]
 [12.93]
 [13.02]
 [24.29]
 [24.31]
 [24.13]
 [24.25]
 [28.88]
 [29.68]
 [28.83]
 [27.9 ]
 [26.48]
 [27.02]
 [26.33]
 [25.36]
 [23.75]
 [24.23]
 [23.67]
 

In [16]:
#y = y.reshape(len(y),1) #do this only for feature scaling for SVR mode

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [9]:
#from sklearn.ensemble import RandomForestRegressor
#regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
#regressor.fit(x_train, y_train)

C:\Users\deepa\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [10]:
#y_pred = regressor.predict(x_test)
#np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[15.15 15.18]
 [10.42 10.32]
 [36.21 37.26]
 [17.02 16.95]
 [32.45 32.26]
 [29.2  27.9 ]
 [28.38 28.18]
 [29.18 28.95]
 [28.81 29.07]
 [23.52 23.8 ]
 [ 6.38  6.4 ]
 [42.67 42.5 ]
 [11.36 11.22]
 [41.96 43.1 ]
 [41.1  41.96]
 [25.67 26.33]
 [10.67 10.7 ]
 [29.29 28.09]
 [14.36 14.65]
 [12.45 12.29]
 [12.69 12.46]
 [32.73 32.71]
 [10.69 10.77]
 [39.41 38.57]
 [ 6.06  6.04]
 [14.64 14.66]
 [12.85 13.  ]
 [13.87 14.41]
 [10.7  10.75]
 [39.75 39.89]
 [12.73 12.74]
 [12.9  12.74]
 [41.74 41.26]
 [12.95 12.77]
 [28.57 28.56]
 [36.92 35.99]
 [14.24 13.97]
 [36.83 35.69]
 [17.13 17.14]
 [10.56 10.85]
 [11.54 11.6 ]
 [39.94 39.97]
 [14.56 14.42]
 [25.87 25.17]
 [19.08 19.5 ]
 [24.29 24.4 ]
 [10.69 13.69]
 [12.7  12.12]
 [28.32 28.86]
 [31.86 32.75]
 [32.54 32.24]
 [12.95 12.97]
 [32.8  32.31]
 [15.15 14.96]
 [36.92 36.95]
 [10.39 10.39]
 [17.7  15.55]
 [27.08 26.19]
 [38.88 40.12]
 [14.53 14.53]
 [14.94 14.72]
 [12.4  12.33]
 [32.46 32.23]
 [10.38 10.34]
 [12.61 12.65]
 [12.15 11.8 ]
 [39.32 38

In [11]:
#from sklearn.metrics import r2_score
#r2_score(y_test, y_pred)
#very good value  r square value

0.9968381918767945

In [12]:
#from sklearn.tree import DecisionTreeRegressor
#regressor = DecisionTreeRegressor(random_state = 0)
#regressor.fit(x_train, y_train)


DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=0, splitter='best')

In [13]:
#y_pred = regressor.predict(x_test)
#np.set_printoptions(precision=2)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[15.16 15.18]
 [10.46 10.32]
 [35.48 37.26]
 [17.41 16.95]
 [32.26 32.26]
 [29.05 27.9 ]
 [28.15 28.18]
 [28.67 28.95]
 [28.4  29.07]
 [22.8  23.8 ]
 [ 6.37  6.4 ]
 [41.67 42.5 ]
 [11.34 11.22]
 [41.64 43.1 ]
 [41.09 41.96]
 [26.89 26.33]
 [10.72 10.7 ]
 [29.14 28.09]
 [14.61 14.65]
 [12.45 12.29]
 [12.87 12.46]
 [32.82 32.71]
 [10.66 10.77]
 [38.67 38.57]
 [ 6.01  6.04]
 [14.71 14.66]
 [13.   13.  ]
 [14.19 14.41]
 [10.7  10.75]
 [40.   39.89]
 [12.8  12.74]
 [12.86 12.74]
 [41.3  41.26]
 [13.   12.77]
 [28.57 28.56]
 [36.95 35.99]
 [14.22 13.97]
 [36.95 35.69]
 [17.14 17.14]
 [10.54 10.85]
 [11.59 11.6 ]
 [39.86 39.97]
 [14.58 14.42]
 [26.   25.17]
 [19.95 19.5 ]
 [24.31 24.4 ]
 [10.67 13.69]
 [12.95 12.12]
 [28.03 28.86]
 [31.84 32.75]
 [32.49 32.24]
 [12.93 12.97]
 [33.24 32.31]
 [14.92 14.96]
 [36.95 36.95]
 [10.36 10.39]
 [15.55 15.55]
 [26.97 26.19]
 [38.33 40.12]
 [14.47 14.53]
 [14.9  14.72]
 [12.35 12.33]
 [32.21 32.23]
 [10.37 10.34]
 [12.63 12.65]
 [11.98 11.8 ]
 [39.04 38

In [15]:
#from sklearn.metrics import r2_score
#r2_score(y_test, y_pred)

0.9967202480465667

In [18]:
#from sklearn.preprocessing import StandardScaler
#y = y.reshape(len(y),1)
#sc_x = StandardScaler()
#sc_y = StandardScaler()
#x_train = sc_x.fit_transform(x_train)
#y_train = sc_y.fit_transform(y_train)

In [19]:
#from sklearn.svm import SVR
#regressor = SVR(kernel = 'rbf')
#regressor.fit(x_train, y_train)

C:\Users\deepa\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [20]:
#y_pred = sc_y.inverse_transform(regressor.predict(sc_x.transform(x_test)))
#np.set_printoptions(precision=2)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[16.23 15.18]
 [10.49 10.32]
 [35.33 37.26]
 [23.57 16.95]
 [32.72 32.26]
 [28.07 27.9 ]
 [29.63 28.18]
 [34.89 28.95]
 [28.63 29.07]
 [29.84 23.8 ]
 [ 7.25  6.4 ]
 [40.65 42.5 ]
 [12.53 11.22]
 [40.82 43.1 ]
 [38.12 41.96]
 [25.01 26.33]
 [ 9.92 10.7 ]
 [26.91 28.09]
 [15.37 14.65]
 [11.52 12.29]
 [12.33 12.46]
 [33.07 32.71]
 [ 9.91 10.77]
 [38.12 38.57]
 [ 8.04  6.04]
 [13.6  14.66]
 [13.8  13.  ]
 [14.58 14.41]
 [ 9.31 10.75]
 [35.98 39.89]
 [13.83 12.74]
 [14.21 12.74]
 [39.23 41.26]
 [14.38 12.77]
 [29.42 28.56]
 [37.57 35.99]
 [14.77 13.97]
 [36.32 35.69]
 [18.3  17.14]
 [ 9.9  10.85]
 [12.85 11.6 ]
 [39.42 39.97]
 [14.61 14.42]
 [33.04 25.17]
 [20.02 19.5 ]
 [24.94 24.4 ]
 [10.5  13.69]
 [12.28 12.12]
 [28.25 28.86]
 [31.5  32.75]
 [32.93 32.24]
 [13.48 12.97]
 [32.79 32.31]
 [15.93 14.96]
 [37.28 36.95]
 [10.16 10.39]
 [18.32 15.55]
 [32.79 26.19]
 [37.78 40.12]
 [14.31 14.53]
 [16.2  14.72]
 [11.5  12.33]
 [32.85 32.23]
 [11.17 10.34]
 [11.46 12.65]
 [12.67 11.8 ]
 [38.78 38

In [21]:
#from sklearn.metrics import r2_score
#r2_score(y_test, y_pred)

0.9524246877329057

In [24]:
#from sklearn.preprocessing import PolynomialFeatures
#from sklearn.linear_model import LinearRegression
#poly_reg = PolynomialFeatures(degree = 8)
#x_poly = poly_reg.fit_transform(x_train)
#regressor = LinearRegression()
#regressor.fit(x_poly, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
#y_pred = regressor.predict(poly_reg.transform(x_test))
#np.set_printoptions(precision=2)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[15.02 15.18]
 [10.58 10.32]
 [36.48 37.26]
 [17.35 16.95]
 [32.3  32.26]
 [28.56 27.9 ]
 [28.58 28.18]
 [29.35 28.95]
 [29.46 29.07]
 [22.98 23.8 ]
 [ 5.68  6.4 ]
 [42.65 42.5 ]
 [11.35 11.22]
 [42.4  43.1 ]
 [42.14 41.96]
 [26.28 26.33]
 [10.55 10.7 ]
 [27.98 28.09]
 [14.33 14.65]
 [12.76 12.29]
 [12.62 12.46]
 [32.8  32.71]
 [10.59 10.77]
 [38.95 38.57]
 [ 4.53  6.04]
 [14.83 14.66]
 [12.83 13.  ]
 [13.9  14.41]
 [10.55 10.75]
 [41.17 39.89]
 [12.94 12.74]
 [12.62 12.74]
 [41.61 41.26]
 [12.93 12.77]
 [28.3  28.56]
 [36.98 35.99]
 [14.02 13.97]
 [36.41 35.69]
 [17.44 17.14]
 [10.83 10.85]
 [11.47 11.6 ]
 [39.74 39.97]
 [14.74 14.42]
 [25.63 25.17]
 [18.71 19.5 ]
 [23.96 24.4 ]
 [10.75 13.69]
 [12.46 12.12]
 [28.63 28.86]
 [32.83 32.75]
 [32.54 32.24]
 [12.83 12.97]
 [33.24 32.31]
 [15.01 14.96]
 [37.6  36.95]
 [10.35 10.39]
 [14.99 15.55]
 [25.13 26.19]
 [39.57 40.12]
 [14.74 14.53]
 [14.8  14.72]
 [12.78 12.33]
 [32.18 32.23]
 [10.07 10.34]
 [12.66 12.65]
 [11.87 11.8 ]
 [39.04 38

In [27]:
#polynomial Regression works best but it might be overfitting the data
#from sklearn.metrics import r2_score
#r2_score(y_test, y_pred)


0.9974572124957924

In [28]:
#from sklearn.linear_model import LinearRegression
#regressor = LinearRegression()
#regressor.fit(x_train, y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [29]:
#y_pred = regressor.predict(x_test)
#np.set_printoptions(precision=2)#
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[17.41 15.18]
 [ 8.01 10.32]
 [29.44 37.26]
 [25.83 16.95]
 [31.09 32.26]
 [27.46 27.9 ]
 [28.26 28.18]
 [34.11 28.95]
 [29.38 29.07]
 [28.49 23.8 ]
 [ 6.97  6.4 ]
 [35.2  42.5 ]
 [11.77 11.22]
 [35.38 43.1 ]
 [35.86 41.96]
 [26.59 26.33]
 [ 9.43 10.7 ]
 [27.3  28.09]
 [15.98 14.65]
 [12.29 12.29]
 [13.16 12.46]
 [31.25 32.71]
 [ 9.5  10.77]
 [32.43 38.57]
 [ 5.69  6.04]
 [15.26 14.66]
 [13.01 13.  ]
 [14.47 14.41]
 [ 9.11 10.75]
 [32.91 39.89]
 [13.21 12.74]
 [14.42 12.74]
 [35.56 41.26]
 [14.26 12.77]
 [28.44 28.56]
 [36.94 35.99]
 [14.15 13.97]
 [37.26 35.69]
 [18.47 17.14]
 [ 9.74 10.85]
 [11.47 11.6 ]
 [32.39 39.97]
 [15.77 14.42]
 [31.24 25.17]
 [24.01 19.5 ]
 [25.47 24.4 ]
 [ 9.75 13.69]
 [13.11 12.12]
 [27.8  28.86]
 [32.51 32.75]
 [31.23 32.24]
 [12.71 12.97]
 [34.07 32.31]
 [17.75 14.96]
 [37.1  36.95]
 [ 7.83 10.39]
 [23.01 15.55]
 [30.92 26.19]
 [32.68 40.12]
 [16.27 14.53]
 [17.39 14.72]
 [12.31 12.33]
 [31.39 32.23]
 [ 8.49 10.34]
 [12.13 12.65]
 [11.18 11.8 ]
 [32.37 38

In [30]:
#from sklearn.metrics import r2_score
#r2_score(y_test, y_pred)

0.9085551235120667